Find proc address for glEGLImageTargetTexture2DOES during runtime
liri-archive/eglfs pull request #9
Opened 2019-01-03 20:14 UTC by schnitzeltony

glEGLImageTargetTexture2DOES is not defined in the symbol table in newer
versions of mesa.

fixes:
| liri-shell: symbol lookup error: /usr/lib/plugins/liri/egldeviceintegrations/libeglfs-kms-integration.so: undefined symbol: glEGLImageTargetTexture2DOES

Inspired by [1] / addresses [2]

[1] https://github.com/intel/libyami/commit/394dd742c40333336b3eb197c627db4239b93e84
[2] https://github.com/lirios/eglfs/issues/8

Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>

2019-01-03 23:01 UTC, plfiorini requested changes

2019-01-03 23:01 UTC, plfiorini commented on src/plugins/platforms/eglfs/deviceintegration/eglfs_kms/qeglfskmsgbmscreen.cpp
> +static PFNGLEGLIMAGETARGETTEXTURE2DOESPROC imageTargetTexture2DProc = NULL;
```suggestion
 static PFNGLEGLIMAGETARGETTEXTURE2DOESPROC imageTargetTexture2DProc = nullptr;
```

use `nullptr` instead

2019-01-03 23:01 UTC, plfiorini commented on src/plugins/platforms/eglfs/deviceintegration/eglfs_kms/qeglfskmsgbmscreen.cpp
> +    }
nitpick: no curly braces for one line instructions

2019-01-03 23:01 UTC, plfiorini commented on src/plugins/platforms/eglfs/deviceintegration/eglfs_kms/qeglfskmsgbmscreen.cpp
> +            (PFNGLEGLIMAGETARGETTEXTURE2DOESPROC) eglGetProcAddress("glEGLImageTargetTexture2DOES");
```suggestion
             reinterpret_cast<PFNGLEGLIMAGETARGETTEXTURE2DOESPROC>( eglGetProcAddress("glEGLImageTargetTexture2DOES"));
```

2019-01-03 23:01 UTC, plfiorini commented on src/plugins/platforms/eglfs/deviceintegration/eglfs_kms/qeglfskmsgbmscreen.cpp
> +    imageTargetTexture2D(GL_TEXTURE_2D, image);
Actually since `glEGLImageTargetTexture2DOES` is used only here you can do like `qeglfskmsgbmwindow.cpp` does:

```suggestion
PFNGLEGLIMAGETARGETTEXTURE2DOESPROC imageTexture2D =
    reinterpret_cast<PFNGLEGLIMAGETARGETTEXTURE2DOESPROC>(eglGetProcAddress("glEGLImageTargetTexture2DOES"));
if (imageTexture2D)
    imageTexture2D(GL_TEXTURE_2D, image);
else
    qCritical("No glEGLImageTargetTexture2DOES function available");
```

2019-01-04 00:45 UTC, schnitzeltony commented
Hope I reduced your suggestions correctly

2019-01-05 00:23 UTC, plfiorini approved these changes

2019-01-05 00:23 UTC, merged